### PR TITLE
migrations to 0.17 and 0.18

### PR DESCRIPTION
**Pull request by aische**
I closed the old pull request because the version numbers were messed up. I added version 1.0.3 (elm-0.17) and 1.0.4 (elm-0.18). Interested to merge this and publish it?

### CODE REVIEW

**Comment by ghost** [comment]
Any specific reason why you closed this?

**Comment by aische** [comment]
Hi, I just read about the process of publishing packages and I fear the version numbers are still wrong. I think the code I wrote is ok, but the version tags might not get accepted. I am not sure because I never published an official elm package. I hope you can fix it if necessary. Thank you!

**Comment by ghost** [comment]
Sure, no problem, we'll fix it; and no thank you! :-)

**Comment by cmarfia** [comment]
Do you have an update on when this will be published for 0.18? 

I would love to use this library .

**Pull request closed without merging**
